apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80          # Service port
      targetPort: 5000  # Container port
      nodePort: 30080   # NodePort (external port)
